### PR TITLE
CD PA1010D as GPS sensor

### PR DESCRIPTION
**Pull request by aentinger**
The CD PA1010D is a GPS sensor with tiny footprint and integrated patch antenna which can be interfaced with both UART and I2C. A [breakout board](https://www.adafruit.com/product/4415) is available (I've already ordered one).

adafruit_products_Mini_GPS_PA1010D_SCh

@generationmake What do you think about this sensor? It's tiny form factor means we can easily fit it onto the Baseboard, where space will be at a premium.

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger ,
there exist similar modules like the Quectel L80-R ( https://www.quectel.com/product/l80r.htm ) or u-blox SAM-M8Q ( https://www.u-blox.com/en/product/sam-m8q-module ). I think all these modules have similar performance.
GNSS modules show the best performance when they have a clear view of the sky. With our baseboard this is not possible. The module must be mounted on the top side (facing the sky). But this side of the baseboard is blocked by the structural frame of the quadcopter. So I see some problems using this module.

**Comment by aentinger** [comment]
That's actually a good point. On the other hand, the frame of the quadcopter is quite small (at least of the Armattan one) and the camera module is already protruding from the frame. In a similiar way the GPS module could also be protruding from the quadcopter frame. Of course a module with antenna would be better.

**Comment by generationmake** [comment]
Hi @aentinger I added a 3d model of the quadcopter to show its dimensions. 
I think it would be OK if the GPS module is mounted on the side of the mainboard so it has a least partial view of the sky.

**Comment by aentinger** [comment]
Good Morning @generationmake :wave: Thank you for the rendering, it looks fantastic. It also helps to put the dimensions of everything into perspective. I now think it would better to use a module with has an external antenna connector such that a patch antenna can be put on top of the quadcopter frame. Does the modules suggested by you have breakout boards and example code?

**Comment by generationmake** [comment]
"My" gps modules also have an onboard antenne. Maybe we can make an option to use both: modules with onboard antenne and modules with antenna connector.

At the moment the design is only a rough estimation.  The only exact dimension is the distance of the motors. I will update it as soon as I get the real hardware to make some measurements.

Tonight I am going to make the first (mechanical) draft of the baseboard so we can see the position of all parts.

**Comment by generationmake** [comment]
Hi @aentinger I started the baseboard.
It now has a dimension of 100 x 100 mm. Until now there are only the Arduino MKR connector, the ToF sensors and the gps module placed. I used an u-blox SAM because I had that part already in the library. The other gps modules are similar. As you can see the module is beside the frame and it has some view of the sky. But this view is also blocked by the battery and the top frame.

Next I will try to add the motors and motor controllers.

**Comment by aentinger** [comment]
Hi @generationmake :wave: That's fantastic 😀 At first 10x10 cm sounded really large to me but looking at the 3D renderings it looks okay. Still - if the board could be in something else than rectangular shape (kind of following the contours of quadcopter arms) it would be probably beneficial for air flow. Also we still need some space on the arms for mounting the ESCs.

**Comment by aentinger** [comment]
Following up on a email discussion with @generationmake I'm merging this PR for now.

**Pull request merged**
