### PR TITLE
Requirements for Viper Baseboard

### PR DESCRIPTION
**Pull request by aentinger**
This pull request add the requirements for the viper baseboard to the repositories README.

### CODE REVIEW

**Comment by lxrobotics** [comment]
After giving the ToF sensor concept some consideration I've come to the conclusion that 2 ToF sensors is an unfavorable number. Either you take three sensors and use them to roughly determine the orientation of the quadcopter to ground (instead of only determining the distance between quadcopter and ground) or you use one sensor only and assume a straight floor. Two sensors are not enough for determination of ground orientation and are also too few to build any kind of error resilience into the system (e.g. a 2-out-of-3 decision is only possible with three sensors). Therefore I conclude that one sensor (per type) is sufficient. What's your opinion @generationmake ?

**Comment by lxrobotics** [comment]
@generationmake :wave: After doing some more research I've discovered that the VL53L0X have a measurement range of 0 - 2 m while the VL6180X only have a measurement range of 0 - 0.6 m. Both have a resolution of 1 mm. Therefore I suggest eliminating the VL6180X completely and using only VL53L0X. What are your thoughts on this?

**Comment by generationmake** [comment]
@lxrobotics I agree. Either use one distance sensor and assume an even floor or use a minimum of three sensors to determine the orientation of the floor and even be able to avoid landing on unsuitable terrain. I would prefer having three sensors. They should be placed in an equilateral triangle to simplify the calculations.

Regarding measurement distance: it depends. if you want to use the sensors to avoid collision with the ground you have to limit the sink rate according to the measurement distance and the dynamics of the copter. So VL6180X would also be OK but it limits the speed of the copter. VL53L0X is better. But to get a really high dynamic behavior this still is not enough. One approach would be to use the small ToF sensor only for landing and close to ground navigation and use another sensor to measure height over ground.

**Comment by lxrobotics** [comment]
@generationmake Thank you very much for your input :wink: I've added a new functional requirements concerning vertical stabilisation which is performed via ToF when close to ground and altimeter when further away from ground. I've also increased the number of ToF sensors within the block diagram to 3 so we can use it for ground surface estimation. Just one thought - since the quadcopter anyway has 4 arms, wouldn't it make sense to go for 4 sensors instead and put one under each quadcopter arm so to say?

**Comment by generationmake** [comment]
I think four sensors is also fine. And if they are arranged as a square the calculations for the orientation should also be easy.
But how does the copter how far it is away from ground. If it is flying over hills and it only relays on the barometric sensor and the ground is coming closer and closer? Will it have some local map of the heights or am I thinking to complicated?

Regarding the camera: Why do you want to use a OV2640 module and not the MIPI camera module which can be directly connected to the Vidor 4000.

**Comment by lxrobotics** [comment]
In my opinion the ground distance sensors will always be active. As soon as they detect ground their measurement overrides any decisions derived from the altimeter (especially since the altimeter is pressure dependent and might show different heights when the atmospheric pressure changes). The reason I'd like to use the OV2640 is because I'd like to keep MIPI camera module connector free for a forward facing camera where the signal is encoded in the FPGA and transmitted via WiFi (not sure if this is feasible with the available FPGA ressources though).

**Comment by generationmake** [comment]
I worry if we run out of pins. The OV2640 needs about 16 IO pins. And the no more pins for the other functions of the baseboard would be left. One option could be to use the MiniPCI Express connector because it has plenty of unused pins. Unfortunately we can't rely solely on the MiniPCI Express conntor because it has no pin to feed the 5V supply voltage. So we have to use a combination of MiniPCI Express connector and MKR connector. But this has some mechanical challenges. At the moment I can't imagine a useful and easy way how to connect to both connectors at the same time with one motherboard.

**Comment by aentinger** [comment]
Hi @generationmake :wave: I haven't counted the required pins yet but I can see what you mean by a mechanical challenge using both MKR pins and MiniPCIe connector. In your email you mentioned that maybe you see a way now for both using MKR pins and MiniPCIe connector - could you elaborate on this? If we can't use MKR + MiniPCIe we might use the MIPI camera connector instead and sacrifice the forward looking camera for the downward looking one. What do you think?

**Comment by generationmake** [comment]
@aentinger I uploaded an image with an possible stacking of PCBs. the blue one is the Vidor 4000 (unfortunately i couldn't find a 3D model of it). The green one is the baseboard connected to the copter. The red one is an additional board which connects to the minipcie connector and could carry the OV2640. The stacking height using the MKR connectors is about 11 mm. The stacking height of the mpcieconntor is only 2 to 4 mm if you use a small socket. So the red board should easily fit in between. the red board can be fixed using the left two screw holes of the vidor 4000.

**Comment by aentinger** [comment]
Good Morning @generationmake :wave: This sounds like a reasonable idea. I have another question: Would it not be possible to "bridge" the MiniPCIe pins to the (green) baseboard using Samtec Board-2-Board connectors? I know they are available in various lengths so there should also be one available fitting between (red) adapter board and green baseboard. The advantage would be that both the (blue) Vidor would be mounted more stable to the (green) baseboard and less mechanical strain would be put on the (blue) Vidor MKR connectors to keep the Vidor mounted to the (green) baseboard.

**Comment by generationmake** [comment]
Good Morning also to you, @aentinger ! This is definitely possible. However Samtec connectors are always very expensive and difficult to solder. Additionally I think we don't need any electrical connection between the red board and the green board if we connect the OV2640 directly to the red board. But we can mount the red board on the green board using spacers like this one: https://www.we-online.de/katalog/de/SMSI_SMT_STEEL_SPACER_M3_THREAD_INTERNAL/ There are also different heights available.
I think both solutions are equally usable.

BTW: Do you know a source for a 3D model of the Vidor 4000 so we get all the distances and holes correct?

**Comment by aentinger** [comment]
Steel spacers are a good idea, if we don't need additional connections from the MiniPCIe to the baseboard then there is indeed no need for Samtec connectors. Regarding dimensions, I've found this [DXF file](https://content.arduino.cc/assets/MKR_VIDOR_4000_AssemblyTop.dxf) with the board dimensions. Please let me know if you need more information.

**Comment by generationmake** [comment]
dxf file is fine but real 3D model is always better because it also has height information on components and connectors.

Do we already have a decision which OV2640 module we want to use (manufacturer/part number)? Does this module have to be mounted in the center (of gravity)?

**Comment by aentinger** [comment]
To my best knowledge there is no 3D model of the MKR VIDOR 4000 available :disappointed: 

Regarding the OV2640 module - what do you think of this [one](https://www.arducam.com/product/2mp-ov2640-camera-module/)?

**Comment by per1234** [comment]
I'm not sure whether it would be of any use to you, but there is a fellow selling 3D Blender models of MKR boards for $15. No MKR Vidor 4000 currently, but they say they're open to requests:
- https://sketchfab.com/3d-models/mkr-wifi-1010-241616d14c6c48299fa09b15107b6c5a
- https://forum.arduino.cc/index.php?action=profile;u=1346394

**Comment by generationmake** [comment]
@per1234 Thanks for the links. The models are nice but I fear we might run into licensing issues when we publish data on our PCBs as the models will somehow be included.

@aentinger There are 2 versions of the camera module available. I suppose we use the one with the M12 lens, because this has a better lens and better mounting options. The mounting holes with 1.6 mm are a little bit small but I think this will work.

**Comment by aentinger** [comment]
@generationmake Please select the module which you think best :wink: The mounting location of the camera on the quadcopter does not matter much, since the position of the camera is fixed with reference to the quadcopter center we can always translate the sensor output to the right coordinate frame.
There is one more thing which came to my mind - we need I2C connections from the camera to the MCU (not to the FPGA), because the camera is configured via I2C. I don't know if MCU I2C pins are exposed on MiniPCIe connector, if they are not we might need connections to the baseboard after all.

@per1234 Thank you for the input. The MKR WIFI 1010 sure looks nice. @generationmake is mostly concerned with mechanical dimensions though, not sure how accurate the blender sketches are.

**Comment by generationmake** [comment]
I added a new repository for the development of the camera adapter: https://github.com/107-systems/VidorCameraAdapter
There is a branch called dev_v0.1 and I suggest to discuss topics regarding this adapter there.

**Comment by aentinger** [comment]
Good evening @generationmake :wave: Although the requirements are still somewhat more high-level than I like I'd suggest to merge this pull request for now because the requirements are good enough to guide the direction of the project. What do you think about it?

**Comment by generationmake** [comment]
Hi @aentinger 
I would like to redraw the block diagram to represent the situation with the VidorCameraAdapter. And maybe add a preliminary pin out table of the MKR connector.
give me two more days ...

**Comment by aentinger** [comment]
Hi @generationmake :wave: This is totally fine by me :wink: . Take your time.

**Comment by generationmake** [comment]
Good morning @aentinger : I updated description and block diagram and now it is fine for me.

**Comment by aentinger** [comment]
Hi @generationmake :wave: Thank you very much for incorporating your changes. One word on the resolution/size of the generated PNG file - the size of the PNG depends on it's size on your monitor. So if you want a big sized PNG (which would be better to see in the README) you need to export to PNG on a big monitor. Right now I don't have available, maybe you can fix it before I get to a big monitor myself. In any case I'll be merging this PR now.

**Pull request merged**
